### ISSUE TITLE
Kotlin compile task executes before Wire task

### ISSUE THREAD

**Issue by EddieRingle** [square/wire-gradle-plugin#7]
I have a Java library module that also uses the vanilla Kotlin Gradle plugin. In order for my Kotlin sources to see the generated Wire classes correctly, the following must be added to my build.gradle:

``` gradle
sourceSets.each { set ->
    def taskNamePart = "main".equals(set.name) ? "" : set.name
    def ktTask = project.tasks.getByName("compile${taskNamePart.capitalize()}Kotlin")
    def wireTask = project.tasks.getByName("generate${taskNamePart.capitalize()}WireProtos")
    ktTask.dependsOn(wireTask)
}
```

This could easily be added to the `applyJava()` method in `WirePlugin`, but it seems like that's a slippery-slope solution considering there are probably other plugins that might need this workaround.

Is that the only way, or is there some Gradle black magic I'm unaware of that could solve this nicely?

**Comment by EddieRingle** [comment]
I've submitted PR #8 with the simple solution described above.

**Comment by JakeWharton** [comment]
What about Scala? Groovy? Clojure? This isn't a scalable solution to put in this project. I think you just have to fix it in your build. Score 1 for maven for having an explicit phase for code gen.

**Comment by EddieRingle** [comment]
Yeah, that's the slippery slope I'm talking about. :\

**Comment by JakeWharton** [comment]
The current Java approach seems out of order. We need Wire's code-gen to run before compilation. The forthcoming integration tests will help here. I'm holding off taking any approach until we have those.

**Comment by EddieRingle** [comment]
@JakeWharton How about #9?
